### ISSUE TITLE
How to use this lib with Laravel

### ISSUE THREAD

**Issue by pacoorozco** [Badcow/DNS#19]
Hi,

I'm developing a [DNS Management app with Laravel](https://github.com/pacoorozco/probind). I'd like to use your lib in order to deal with DNS records. This will improve resource record validation and get a more ordered way to design my app structure.

But I don't know how to use your lib with Eloquent / Model model. I suppose I can extend Model with your Rdata models, but I don't know It's the best way. 

For example: When an user submit a new record form, We don't know what Rdata to use... I suppose I can use a switch case for each one, Isn't it?

Thanks in advance.

**Comment by samuelwilliams** [comment]
Hi @pacoorozco 

I'm not familiar with Laravel, as I primarily dealt with Symfony when I was a full-time developer.

If I were developing a Symfony app, I would be defining special form types for use with the form input. I'm not sure how that translates with Laravel.

In terms of model, maybe have a single class that represents all RData types and can internally switch between the required concrete classes and return populated RData classes.

I'm not sure of the best advice to give you. Maybe send some code to me so that I know the direction that you want to go.

Cheers,

Sam
